### PR TITLE
Integrate Map component in Create event form.

### PR DESCRIPTION
**Pull request by namrathaov**
To test: 

Go to create event tab: View map component rendered with pins.
View the form styled to match the app theme.
Test if create event form works as expected.

### CODE REVIEW

**Comment by Vutsuak16** [comment]
where is CreateEvent.css file?
It is giving import error

**Review by Kanchan-Wakchaure — CHANGES_REQUESTED** [review]
Map is not displayed because of missing key. Please update README for required steps

**Comment by namrathaov** [comment]
Added readme instruction for google api key and missing css file.

**Review by Vutsuak16 — APPROVED** [review]
works

**Review by raisa-khatun — COMMENTED** [review]
Works as expected.

**Review by gaddevmounika — APPROVED** [review]
Looks good to me. Everything's working fine.Just make sure the footer doesn't overlap with the map.

**Pull request merged**
