### PR TITLE
Us 12 task 138

### PR DESCRIPTION
**Pull request by Kanchan-Wakchaure**
1. Add a marker by clicking on the map
2. Get the create event pop-up by clicking on the marker

### CODE REVIEW

**Review by raisa-khatun — COMMENTED** [review]
Works expected feature-wise.
Things to consider:
1. It woulbe be better if you can remove this warning.
warning
2. Remove the address field from form.
3. There is a bit space at bottom below the map. That could be removed.

**Review by namrathaov — CHANGES_REQUESTED** [review]
Works great to add pin on the map and create event. 
From usage perspective, it's not obvious that I need to click on map then again click on marker. Needs some improvement on that.
1. Marker should be different color with plus icon maybe.
2. There can be a default location when the map loads.
3. Create event form is not cleared on clicking the marker. 
4. Map should be in retro style. 
5. Map size at the bottom of the page
6. End point should be create event, not map container.

Other changes needed in the form:
7. Should not be able to create events for the past (before today)
8. Can try to make the form pop-up as soon as marker is placed.

**Comment by Kanchan-Wakchaure** [comment]
Works great to add pin on the map and create event.
From usage perspective, it's not obvious that I need to click on map then again click on marker. Needs some improvement on that.
 => As we discussed and decided on the flow of adding marker to the map on click and then getting 
       pop-up by on click on marker, the requested change is not in the scope of this PR.

1. Marker should be different color with plus icon maybe.
2. There can be a default location when the map loads.
  => Map is centered with default location.
3. Create event form is not cleared on clicking the marker.
 => As I have mentioned in the team meeting, we will have to resolve these issues after PR is merged. It is not going to impact anything for now if we merge this PR.
4. Map should be in retro style.
   => This would be additional change which would be added in another PR.
5. Map size at the bottom of the page
  => Similar to earlier comment, we will need to fix it after PR is merged
6. End point should be create event, not map container.
 => we are not using create event component anymore, instead we are using MapContainer for add event feature.
 Other changes needed in the form:
7. Should not be able to create events for the past (before today)
 => This is out of scope of this PR
 8. Can try to make the form pop-up as soon as marker is placed.
 => It would not be feasible solution since user could click on wrong location and he/she should first need to confirm on location before getting a create event pop-up.

**Comment by Kanchan-Wakchaure** [comment]
Works expected feature-wise.
Things to consider:
1. It woulbe be better if you can remove this warning.
 warning
2. Remove the address field from form.
 => We cannot remove it as location is required for creating event and it is better to show the address to user as well.
 3. There is a bit space at bottom below the map. That could be removed.
 => As discussed in team meeting, we will need to work on fixing small issues in this feature after we merge the PR.

**Comment by raisa-khatun** [comment]
Ok to be merged for now.

**Pull request merged**
