### PR TITLE
Us 62 task 70

### PR DESCRIPTION
**Pull request by raisa-khatun**

### CODE REVIEW

**Comment by raisa-khatun** [comment]
Run it as per the readme says
To test go to http://127.0.0.1:8000/api/events/  in postman.
Post the form with below field:
                 title: '',
                date: '',
                time:'',
                duration: '',
                source: '',
                destination: ''

To see the created event go to travlendar_app_event in db.

**Review by namrathaov — COMMENTED** [review]
The api matches the request payload from frontend. API responses are handled correctly. Looks good to be merged.

**Comment by raisa-khatun** [comment]
Merged frontend and backend for create event. It is working as expected. To test go to create event page, fill the form and create an event. Then go to http://127.0.0.1:8000/api/events/  in postman to see the newly created event appended at bottom.

**Review by namrathaov — APPROVED** [review]
Tested the create event end to end. Works well with the frontend form.

**Review by Kanchan-Wakchaure — APPROVED** [review]

**Pull request merged**
