### PR TITLE
Merge branch develop us 10 55

### PR DESCRIPTION
**Pull request by raisa-khatun**

### CODE REVIEW

**Comment by Kanchan-Wakchaure** [comment]
Considering this as a basic skeleton for connecting React and Django frameworks and database, I am approving this pull request. Though the refactoring would be required for data model, database schema and front -end in future. 
For basic set-up, code looks fine to me and we can merge it to develop branch.

**Comment by Kanchan-Wakchaure** [comment]
Considering this as a basic skeleton for connecting React and Django frameworks and database, I am approving this pull request. Though the refactoring would be required for data model, database schema and front -end in future.
For basic set-up, code looks fine to me and we can merge it to develop branch.

**Comment by namrathaov** [comment]
@raisa-khatun The compilation instructions worked for me and I was able to compile and test the skeleton code successfully. Thank you for deleting the node modules. Response codes are handled correctly. Looks good to be merged.

**Comment by raisa-khatun** [comment]
Thanks for the reviews. Merging this PR.

**Pull request merged**
