### PR TITLE
Us 61 task 64

### PR DESCRIPTION
**Pull request by gaddevmounika**
Navigation from signup to login page and made changes to UI to make it look better

### CODE REVIEW

**Review by namrathaov — CHANGES_REQUESTED** [review]
Works well for me. 
Dependency missing in package.json:   "@material-ui/icons": "^4.4.3".
Minor change: I would prefer alignment a bit toward center: 
image
Known issues: Navigation to be fixed, does not match UI wire frames discussed.

**Comment by gaddevmounika** [comment]
Added Missing Dependency.

**Review by Kanchan-Wakchaure — CHANGES_REQUESTED** [review]
Please remove login.css file as it is copy of signup.css. We don't need redundant files in master branch

**Comment by gaddevmounika** [comment]
> Please remove login.css file as it is copy of signup.css. We don't need redundant files in master branch

I don't see a signup.css in sprint-2 branch nor in master.

**Review by raisa-khatun — COMMENTED** [review]
Although the UI is not perfect, the login window is not at the middle and 3 buttons are visible at bottom of the page it is ok to merge at this point. Navigation from login page to signup page is working as expected.

**Review by namrathaov — CHANGES_REQUESTED** [review]
@gaddevmounika  Minor change in api call - according to the backend API supported by Django rest auth:

Change axios call - http://127.0.0.1:8000/api/users/login

**Pull request merged**
