### PR TITLE
Us 29 task 124 125

### PR DESCRIPTION
**Pull request by gaddevmounika**
To test:
1. Front end validations for username and password in login page
2. Front end validations for all fields in signup page except address field.
3. I can add validation for address field but it would require the user to follow a specific format every time he enters address. So I wanted to discuss with u guys if we need it or not before I add.
This is the regex code for address
 \s*([0-9]*)\s((NW|SW|SE|NE|S|N|E|W))?(.*)((NW|SW|SE|NE|S|N|E|W))?((#|APT|BSMT|BLDG|DEPT|FL|FRNT|HNGR|KEY|LBBY|LOT|LOWR|OFC|PH|PIER|REAR|RM|SIDE|SLIP|SPC|STOP|STE|TRLR|UNIT|UPPR|\,)[^,]*)(\,)([\s\w]*)\n

### CODE REVIEW

**Review by raisa-khatun — COMMENTED** [review]
I would still say that passward validation in login should not be there.

In signup even if I give correct address it shows me the error. The error message should be more straightforward for address. (example: it should suggest what the exact format is)

Login success and error messages are working as expected.

Rest of the things are working as expected.

**Comment by gaddevmounika** [comment]
**> I would still say that password validation in login should not be there.**
> I can comment that part out if you strongly feel so.But here are my views
I personally felt it would not affect security as the user can see in signup page that password should be of specific format.It would indeed make the job of the user easier as he gets reminded that the password should be of specific format. It would be useful for user as he may have several passwords and this would be a suggestion to make it user-friendly.I also have noticed several websites login pages which give password validations in login.
**> In signup even if I give correct address it shows me the error. The error message should be more straightforward for address. (example: it should suggest what the exact format is)**
> Updated the suggestion message for Address field.

**Review by Kanchan-Wakchaure — COMMENTED** [review]
1. The validation message is coming before user enters complete email or password. The errors should be shown either when user goes to next field or hit login/sign up button

2. The format of errors is not appropriate. Something like shown below was expected for field validation errors: 
image

**Comment by gaddevmounika** [comment]
> 1. The validation message is coming before user enters complete email or password. The errors should be shown either when user goes to next field or hit login/sign up button.
I will look into this one and fix it.
> 2. The format of errors is not appropriate. Something like shown below was expected for field validation errors:
>    image

I first did in line error message but in that case the address field message is going out of the container as it has the format that the address should be in and making the form look very messy.So I don't want to change that.I attached image for reference of the content.We can do one this remove suggestion of address format and just print address invalid message. But that would send invalid addresses to the backend.So I don't want to change it.

**Comment by gaddevmounika** [comment]
> 1. The validation message is coming before user enters complete email or password.

For this since the user has to know how the password should be and how the address format should be while  trying to enter rather than showing him after he finishes entering it is recommended to have it like that. But in next print we can may be put prefixed messages next to those fields and populate error message only after completely entering that field.

**Comment by Kanchan-Wakchaure** [comment]
> > 1. The validation message is coming before user enters complete email or password.
> 
> For this since the user has to know how the password should be and how the address format should be while trying to enter rather than showing him after he finishes entering it is recommended to have it like that. But in next print we can may be put prefixed messages next to those fields and populate error message only after completely entering that field.

=> You should have implemented standard validation pattern that we see in any of the websites.

**Comment by Kanchan-Wakchaure** [comment]
> > 1. The validation message is coming before user enters complete email or password. The errors should be shown either when user goes to next field or hit login/sign up button.
> >    I will look into this one and fix it.
> > 2. The format of errors is not appropriate. Something like shown below was expected for field validation errors:
> >    image
> 
> I first did in line error message but in that case the address field message is going out of the container as it has the format that the address should be in and making the form look very messy.So I don't want to change that.I attached image for reference of the content.We can do one this remove suggestion of address format and just print address invalid message. But that would send invalid addresses to the backend.So I don't want to change it.

=>1.  Where is the image for reference of content?
    2. You should adjust container size accordingly instead of putting everything at the bottom. It won't be difficult to increase size of the container.

**Comment by raisa-khatun** [comment]
Works for me. Ok to be merged.

**Comment by raisa-khatun** [comment]
Although, It could be better..but ok to be merged for now. Works as expected.

**Comment by namrathaov** [comment]
All validations are visible in both signup and login form as required. Minor tweaking is required in styling. Can to be merged for now.

**Pull request merged**
