### PR TITLE
Adding delete feature(both frontend and backend)

### PR DESCRIPTION
**Pull request by raisa-khatun**
Delete an event from agenda page.

### CODE REVIEW

**Review by namrathaov — COMMENTED** [review]
Deleting an event works as expected. 
It might be good to have the delete button slightly bigger and a confirm delete alert before deleting. 
We need to decide if we are allowing user to delete events from the past.

**Comment by raisa-khatun** [comment]
> Deleting an event works as expected.
> It might be good to have the delete button slightly bigger and a confirm delete alert before deleting.
> We need to decide if we are allowing user to delete events from the past.

1. Added confirmation popup before deleting an event. 
2. Delete icon background is bigger on hover.

**Review by gaddevmounika — APPROVED** [review]
Delete button works as expected.Pop-up displayed on clicking on the delete button. Good to merge to Sprint-4. Only concern is I'm still receiving email alert even after the event is deleted.

**Comment by raisa-khatun** [comment]
> Delete button works as expected.Pop-up displayed on clicking on the delete button. Good to merge to Sprint-4. Only concern is I'm still receiving email alert even after the event is deleted.

I fixed the email alert issue. I was using a diff way to get current date as Kaustuv suggested in last sprint but that is not working correctly it seems. It gave me yesterday's date. So, I changed it to how I was fetching current date before and its working for me now.

**Pull request merged**
